first_project/first_app/urls.py
from django.urls import path,re_path
from django.conf.urls import url
from . import views

#TEMPLATE TAGGING
app_name = 'first_app'

urlpatterns = [
    re_path(r'^index/', views.index, name=''),
    re_path(r'formindex/',views.form_name_view,name='form_name'),
    re_path(r'^relative/$',views.relative,name = 'relative'),
    re_path(r'^other/$',views.other,name='other'),
    re_path(r'^register/$',views.register,name='register'),
    re_path(r'^user_login/$',views.user_login,name='user_login')
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls import url
from first_app import views

urlpatterns = [
    url(r'^$',views.templatebase,name='templatebase'),
    re_path(r'^first_app/',include('first_app.urls')),
    url('^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special')
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey('Topic',on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey('Webpage',on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #additional classes
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from .models import UserProfileInfo


def check_for_z(value):
    if value[0].lower() != 'z':
        raise forms.ValidationError("NAME STARTS WITH small z")
class FormName(forms.Form):
    name = forms.CharField(validators=[check_for_z])
    email = forms.EmailField()
    verify_email = forms.EmailField(label = 'ENTER YOR EMAIL AGAIN:')
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("MAKE SURE MAILS MATCH!!")


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .models import Topic,AccessRecord,Webpage
from . import forms
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
# Create your views here.


def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records': webpages_list}
    return render(request,'first_app/index.html',context=date_dict)

@login_required
def special(request):
    return HttpResponse("You are Logged in, Nice!")



@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('templatebase'))


def form_name_view(request):
    form = forms.FormName()
    if(request.method == 'POST'):
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCEEDED")
            print("NAME: "+form.cleaned_data['name'])
            print("EMAIL: " + form.cleaned_data['email'])
            print("TEXT: " + form.cleaned_data['text'])

    return render(request,'first_app/index1.html',{'form':form})


def templatebase(request):
    return render(request,'first_app/templatebase.html')


def other(request):
    return render(request,'first_app/other.html')


def relative(request):
    return render(request,'first_app/relative_url.html')


def register(request):

    registered = False

    if request.method == "POST":
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

    return render(request,'first_app/registration.html',
                  {'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):
    username=""
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('templatebase'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Some one tried to login and failed!!")
            print("Username:{} and password:{}".format(usename,password))
            return HttpResponse("Invalid login details")
    else:
        return render(request,'first_app/login.html',{'username':username})

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>BASE</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="navbar-brand" href="{% url 'templatebase' %}">DJANGO</a></li>
                <li class="nav-item"><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li class="nav-item"><a class="navbar-link" href="{% url 'first_app:register' %}">REGISTER</a></li>
                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a> </li>
                    <li>Welcome {{ user }}</li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">LOGIN</a> </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="="container>
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <img src="{% static 'images/mol.jpg' %}"/>
        <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>
    </head>
    <body>
        <h1>picture of Moltres, Articuno, Zapdos</h1>
        <h2>Here are Access Records</h2>

        <div class="djangotwo">
            {% if access_records %}
                <table>
                    <thead>
                        <th>Site name</th>
                        <th>Date Accessed</th>
                    </thead>
                {% for acc in access_records %}
                <tr>
                    <td>{{ acc.name }}</td>
                    <td>{{ acc.date }}</td>
                </tr>
                {% endfor %}
                </table>
            {% else %}
                <p> NO ACESS RECORDS FOUND</p>
            {% endif %}
        </div>
    </body>
</html>

first_project/templates/first_app/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>FROM INDEX</title>
</head>
<body>
    <h1>FILL THE FORM</h1>
    <div class="container">
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
</body>
</html>

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Login</h1>
        <form action="{% url 'first_app:user_login' %}" method="post">
            {% csrf_token %}
            <label for="id_username">Username:</label>
            <input type="text" id="id_username" name="username" placeholder="Enter Usename">

            <label for="id_password">Password:</label>
            <input type="password" id="id_password" name="password" placeholder="Enter Password">

            <input type="submit" value="Login">
        </form>
    </div>
{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Welcome to Other</h1>
</body>
</html>

first_project/templates/first_app/registration.html
{% extends 'first_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering</h1>
    {% else %}
        <h1>Register Here</h1>
        <h3>Fill out the form:</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}

first_project/templates/first_app/relative_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Welcome to REALTIVE URL</h1>
    <a href="{% url 'first_app:other' %}">OTHER HTML</a><br>
    <a href="{% url 'admin:index' %}">GO TO ADMIN</a>
    <a href="{% url 'first_app:index' %}">GO TO INDEX</a>
</body>
</html>

first_project/templates/first_app/templatebase.html
{% extends 'first_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}